# Generated by Django 4.0 on 2021-12-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_customerprofile_user_alter_ownerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', related_query_name='room', to='room.hotel'),
        ),
    ]
