# Generated by Django 4.0 on 2021-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_reserved_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='to_date',
            field=models.DateField(),
        ),
    ]
