# Generated by Django 4.0 on 2021-12-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_alter_reserved_from_date_alter_reserved_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveds', related_query_name='reserved', to='room.room'),
        ),
    ]
